import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.scss";
import { SessionProvider } from "next-auth/react";
import Header from "../components/header/Header";
import { BasketProvider } from "@/contexts/BasketContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { FavoritesProvider } from "@/contexts/FavoritesContext";
import { auth } from "@/auth";
import Footer from "@/components/footer/Footer";
// import Deal from "@/components/deal/Deal";
// import Contact from "@/components/contact/Contact";
import HowItWorks from "@/components/howItWorks/HowItWorks";
import Banner from "@/components/banner/Banner";
import Faqs from "@/components/faq/Faqs";
import ContactForm from "@/components/contactForm/ContactForm";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en">
      <head>
        
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionProvider session={session}>
          <AuthProvider>
            <BasketProvider>
              <FavoritesProvider>
              
                <Header />
                {children}
                 
                <HowItWorks />
                <Banner />
                <Faqs />
                <ContactForm />
                <Footer />
              </FavoritesProvider>
            </BasketProvider>
          </AuthProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
