import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.scss";
 
import { SessionProvider } from "next-auth/react";
import Header from "../components/header/Header";
import { BasketProvider } from "@/contexts/BasketContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { FavoritesProvider } from "@/contexts/FavoritesContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionProvider>
          <AuthProvider>
            <BasketProvider>
              <FavoritesProvider>
                <Header />
                {children}
              </FavoritesProvider>
            </BasketProvider>
          </AuthProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
